source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

#only 9.0 supports custom user agent
platform :ios, '10.2'

target 'IMKitSDK_Example' do
  pod 'IMKitIOS', :path => '../'

  target 'IMKitSDK_Tests' do
    inherit! :search_paths

    
  end
end
